### ISSUE TITLE
Calc plugin should copy to clipboard when ENTER is pressed

### ISSUE THREAD

**Issue by jaysonthepirate** [vutran/dext#101]
A common use for a calculator is taking the number and copying it into some form or document. If I use dext as a calculator this isn't possible as clicking away from dext erases the answer.

**Comment by vutran** [comment]
We should add a new plugin action that allows copy to clipboard. I believe @adnasa made a PR in the past for this here: #39.

It may be worth it to re-open that since I can see this being useful for [dext-emoji-plugin](https://github.com/vutran/dext-emoji-plugin) as well since.

**Comment by adnasa** [comment]
I recall that we discussed that we should copy through __mods__ and not through a specific action defined by the plugin

**Comment by vutran** [comment]
`mod` was for alternative title/subtitle/args.

We went with the Alfred flow if <kbd>cmd</kbd> + <kbd>c</kbd> instead of <kbd>enter</kbd> but since some of our plugins doesn't necessarily require an action of `openurl` or `exec`, it may make sense to expose the implementation you did previously as well. I think this will provide a better user experience since some people may just hit <kbd>enter</kbd> and assume it did something.
