### ISSUE TITLE
Plugin API: renamed execute to search?

### ISSUE THREAD

**Issue by vutran** [vutran/dext#52]
A bit going back on my words (#11) but it may make more sense to renamed `execute` to `search`.

This would allow us to use `execute` in the future for executing a specific item.

Example would be something like this:

```js
module.exports = {
  search: q => {
    items: [], // list of ietms
  },
  execute: item => {
    // executes for the selected item...
  },
};
```

This will be a breaking change but since it's still early, we should migrate and just alias/deprecate `execute`.

**Comment by adnasa** [comment]
I think migrating `executing` a targeted item is a good idea and I'm all for this! 👍 

However, I don't agree that `search` is the right term here because I don't see <kbd>dext</kbd> only to be used for search purposes to different source, although that's what we do today and so far a which is a good first step.

I would prefer `query`, because then it is ambigious, generic and every plugin can interpret how they want to react to a query.

**Comment by adnasa** [comment]
@vutran Changed this from discussion to enhancement, since I take that we proceed with this (?)

**Comment by vutran** [comment]
Yeah, we can proceed with this for next release.

**Comment by adnasa** [comment]
After looking further, I'm not sure [whether this](https://github.com/vutran/dext/blob/develop/app/main/index.js#L59-L75) makes sense anymore if we let plugins execute their own item

**Comment by vutran** [comment]
`execute` currently returns/resolves an object of `items`. This is different from the actual execution of a single item. The goal of this issue was to allow `query` be our new endpoint to return these items and delegate `execute` for something else in the future.

**Comment by vutran** [comment]
Closing.
